# Generated by Django 2.2.4 on 2019-12-02 22:12

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtfapi', '0002_auto_20190829_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('description', models.TextField(max_length=512, verbose_name='Description')),
                ('internal_notes', models.TextField(blank=True, help_text='These notes are only useful here, in the admin panel, and are never revealed as public data. Use this space to take all the notes you need about this POI.', null=True, verbose_name='Internal Notes')),
                ('boundaries', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Boundaries')),
                ('deleted_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('managers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_country_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('description', models.TextField(max_length=512, verbose_name='Description')),
                ('internal_notes', models.TextField(blank=True, help_text='These notes are only useful here, in the admin panel, and are never revealed as public data. Use this space to take all the notes you need about this POI.', null=True, verbose_name='Internal Notes')),
                ('boundaries', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Boundaries')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='wtfapi.Country')),
                ('deleted_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('managers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_province_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
    ]
