# Generated by Django 2.2.4 on 2019-12-02 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wtfapi', '0003_country_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='managers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_country_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='province',
            name='managers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_province_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
